version: '2.4'
services:
  antizapret-vpn:
    image: xtrime/antizapret-vpn:latest
    build: ./
    container_name: antizapret-vpn
    restart: unless-stopped
    network_mode: "host"
    volumes:
      - ./client_keys/:/root/easy-rsa-ipsec/CLIENT_KEY/
      - ./easyrsa3/:/root/easy-rsa-ipsec/easyrsa3/
      # Some domains blocked unofficially: https://ntc.party/t/vpn/129/127
      - ./include-hosts-custom.txt:/root/antizapret/config/include-hosts-custom.txt
    privileged: true
    logging:
      driver: "json-file"
      options:
        max-size: "100k"
        max-file: "1"
